### PR TITLE
Mesh Gradient

### PR DESCRIPTION
**Pull request by mikepenz**
Introduce new shader `MeshGradient`

### CODE REVIEW

**Comment by JavierSegoviaCordoba** [comment]
Is there a video about the new `MeshGradient`?

**Comment by mikepenz** [comment]
You can watch it in the browser here: https://mikepenz.github.io/HypnoticCanvas/ 
This one can be easily modified to use different colors

**Comment by JavierSegoviaCordoba** [comment]
Ahh, sorry. I was checking that web from mobile but it does not load (at least on Safari).

**Comment by mikepenz** [comment]
I believe wasm on Safari isn't yet fully functional.

**Pull request merged**
